# Generated by Django 4.1.1 on 2022-11-24 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SBfinder', '0002_userinfo_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='avatar',
            field=models.ImageField(default='default.jpg', upload_to=''),
        ),
    ]
