# Generated by Django 4.1.1 on 2022-11-24 05:19

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('SBfinder', '0003_alter_userinfo_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='avatar',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, default='default.jpg', force_format=None, keep_meta=True, null=True, quality=-1, scale=None, size=[500, 300], upload_to=''),
        ),
    ]
