# Generated by Django 4.1.1 on 2022-11-27 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SBfinder', '0004_alter_userinfo_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='major',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='year',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
